language: 
  - cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

  
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./tools/Linux/premake5 gmake && pushd build/gmake/ && make config=release_x64 && popd; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./tools/MacOS/premake5 gmake && pushd build/gmake/ && make config=debug_x64 && popd; fi